controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . 4 4 4 4 4 4 4 . . . . . 
        . 4 4 4 4 2 2 2 2 2 2 4 . . . . 
        . 4 4 2 5 5 5 5 5 5 2 4 . . . . 
        . . 4 4 2 2 2 2 2 2 4 4 . . . . 
        . . . 4 4 4 4 4 4 4 4 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, dino, 200, 0)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy(effects.fire, 500)
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    dino.destroy(effects.warmRadial, 500)
    scene.cameraShake(4, 500)
    game.over(false, effects.melt)
})
let enemy1: Sprite = null
let projectile: Sprite = null
let dino: Sprite = null
dino = sprites.create(img`
    ........................
    ........................
    ...........ccc..........
    ...........cccc.........
    .......ccc..ccccccc.....
    .......cccccc555555cc...
    ........ccb5555555555c..
    .....cc..b555555555555c.
    .....cccb555555ff155555c
    ......cb5555555fff55d55c
    ......b5555555555555555c
    ...cc.b555dd5555bb33bbc.
    ...cccf55ddddd555b3335c.
    .....bdddddddddd55b335c.
    ..cccdddddb55bbddd5555c.
    ..cccdddddb555bbbbcccc..
    ...ccddddddb5555cbcdc...
    ccccbdddddd5cb55cbcc....
    cddddfdddd555dccbbc.....
    .cddddddbdd5d5bbbcc.....
    ..ccdddbbbdd5dcbcfc.....
    ....ccbbcbddddccdddcc...
    ......cccdd555dccccccc..
    ........cccccccc........
    `, SpriteKind.Player)
controller.moveSprite(dino, 200, 200)
dino.setStayInScreen(true)
game.onUpdateInterval(1000, function () {
    enemy1 = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ........ccccc...................
        ......ccbbbbbc..................
        ....ccddbbbbbbf.................
        ...cbbbddbb22bf.................
        ....ffffdbb22bff................
        .......fbbbbbbbf................
        .......fbbbbbbbff...............
        ......ffbbbbbbbbfff.............
        ......f6bbbbbb663ddcc...........
        .....cc66bbbb666dddddc..........
        .....cd36666663dddddddc.........
        .....cddd3333dbddddddbcc........
        .....cddddddddbdddddbbddc.......
        .....cddddddddbbdddbbdddbc......
        ......cddddddddbbdbbddddbbccc...
        ......ccddddddddbbbbcccccbbbcc..
        .......ccddddddddddddddbccffff..
        ........cccbddccbddddbbfff......
        ........c333bb333cbbfff.........
        ........c33cc32cc3fff...........
        `, SpriteKind.Enemy)
    enemy1.setVelocity(-100, 0)
    enemy1.setPosition(160, randint(5, 115))
    enemy1.setFlag(SpriteFlag.AutoDestroy, true)
})
